#!/bin/bash

files=(
    bash/.bash_profile
    bash/.profile
    git/.gitattributes
    git/.gitconfig
    git/.gitignore
    haskell/.ghci
    ruby/.gemrc
    tmux/.tmux.conf
    vim/.vimrc
)

for file in "${files[@]}"
do
    ln -sv "$PWD/$file" "$HOME"
done
